// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using VisualNovelGameDB.Data;

#nullable disable

namespace VisualNovelGameDB.Migrations
{
    [DbContext(typeof(VNGDBContext))]
    partial class VNGDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VisualNovelGameDB.Entities.Audio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioPath")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("audio_path");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("character_id");

                    b.HasKey("Id");

                    b.ToTable("AUDIO");
                });

            modelBuilder.Entity("VisualNovelGameDB.Entities.Bgm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BgmPath")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("bgm_path");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("BGM");
                });

            modelBuilder.Entity("VisualNovelGameDB.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CNName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("cn_name");

                    b.Property<string>("ENName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("en_name");

                    b.Property<string>("JPName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("jp_name");

                    b.HasKey("Id");

                    b.ToTable("CHARACTER");
                });

            modelBuilder.Entity("VisualNovelGameDB.Entities.CharacterImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CharacterId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("character_id");

                    b.Property<string>("Path")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("path");

                    b.Property<string>("VerticalPainting")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("vertical_painting");

                    b.HasKey("Id");

                    b.ToTable("CHARACTERIMAGE");
                });

            modelBuilder.Entity("VisualNovelGameDB.Entities.ChoiceOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChoiceCNText")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("choice_cn_text");

                    b.Property<string>("ChoiceENText")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("choice_en_text");

                    b.Property<string>("ChoiceJPText")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("choice_jp_text");

                    b.Property<int?>("CurrentMainlineDialogueId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("current_mainline_dialogue_id");

                    b.Property<int?>("NextMainlineDialogueId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("next_mainline_dialogue_id");

                    b.Property<int?>("OptionCollectionId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("option_collection_id");

                    b.HasKey("Id");

                    b.HasIndex("CurrentMainlineDialogueId");

                    b.HasIndex("NextMainlineDialogueId");

                    b.HasIndex("OptionCollectionId");

                    b.ToTable("CHOICEOPTION");
                });

            modelBuilder.Entity("VisualNovelGameDB.Entities.MainlineDialogue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AudioId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("AudioPath")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("audio_path");

                    b.Property<int?>("BgmId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("bgm_id");

                    b.Property<string>("Chapter")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("chapter");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("character_id");

                    b.Property<int?>("ChoiceOptionCollectionId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("choice_option_collection_id");

                    b.Property<bool?>("HaveRead")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("have_read");

                    b.Property<bool?>("IsBgmChange")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("is_bgm_change");

                    b.Property<bool?>("IsChoicePoint")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("is_choice_point");

                    b.Property<int?>("MainlineTextId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("mainline_text_id");

                    b.Property<int?>("SceneId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("scene_id");

                    b.HasKey("Id");

                    b.HasIndex("AudioId");

                    b.HasIndex("BgmId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ChoiceOptionCollectionId");

                    b.HasIndex("MainlineTextId");

                    b.HasIndex("SceneId");

                    b.ToTable("MAINLINEDIALOGUE");
                });

            modelBuilder.Entity("VisualNovelGameDB.Entities.MainlineDialogue_CharacterImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CharacterId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("character_id");

                    b.Property<string>("CharacterPath")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("character_path");

                    b.Property<int>("MainlineDialogueId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("mainline_dialogue_id");

                    b.HasKey("Id");

                    b.HasIndex("MainlineDialogueId");

                    b.ToTable("MAINLINEDIALOGUE_CHARACTERIMAGE");
                });

            modelBuilder.Entity("VisualNovelGameDB.Entities.MainlineText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CNText")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("cn_text");

                    b.Property<string>("ENText")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("en_text");

                    b.Property<string>("JPText")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("jp_text");

                    b.HasKey("Id");

                    b.ToTable("MAINLINETEXT");
                });

            modelBuilder.Entity("VisualNovelGameDB.Entities.OptionCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("OPTIONCOLLECTION");
                });

            modelBuilder.Entity("VisualNovelGameDB.Entities.Scene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("description");

                    b.Property<string>("ScenePath")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("path");

                    b.HasKey("Id");

                    b.ToTable("SCENE");
                });

            modelBuilder.Entity("VisualNovelGameDB.Entities.ChoiceOption", b =>
                {
                    b.HasOne("VisualNovelGameDB.Entities.MainlineDialogue", "CurrentMainlineDialogue")
                        .WithMany()
                        .HasForeignKey("CurrentMainlineDialogueId");

                    b.HasOne("VisualNovelGameDB.Entities.MainlineDialogue", "NextMainlineDialogue")
                        .WithMany()
                        .HasForeignKey("NextMainlineDialogueId");

                    b.HasOne("VisualNovelGameDB.Entities.OptionCollection", null)
                        .WithMany("ChoiceOptions")
                        .HasForeignKey("OptionCollectionId");

                    b.Navigation("CurrentMainlineDialogue");

                    b.Navigation("NextMainlineDialogue");
                });

            modelBuilder.Entity("VisualNovelGameDB.Entities.MainlineDialogue", b =>
                {
                    b.HasOne("VisualNovelGameDB.Entities.Audio", "Audio")
                        .WithMany()
                        .HasForeignKey("AudioId");

                    b.HasOne("VisualNovelGameDB.Entities.Bgm", "Bgm")
                        .WithMany()
                        .HasForeignKey("BgmId");

                    b.HasOne("VisualNovelGameDB.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId");

                    b.HasOne("VisualNovelGameDB.Entities.OptionCollection", "OptionCollection")
                        .WithMany()
                        .HasForeignKey("ChoiceOptionCollectionId");

                    b.HasOne("VisualNovelGameDB.Entities.MainlineText", "MainlineText")
                        .WithMany()
                        .HasForeignKey("MainlineTextId");

                    b.HasOne("VisualNovelGameDB.Entities.Scene", "Scene")
                        .WithMany()
                        .HasForeignKey("SceneId");

                    b.Navigation("Audio");

                    b.Navigation("Bgm");

                    b.Navigation("Character");

                    b.Navigation("MainlineText");

                    b.Navigation("OptionCollection");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("VisualNovelGameDB.Entities.MainlineDialogue_CharacterImage", b =>
                {
                    b.HasOne("VisualNovelGameDB.Entities.MainlineDialogue", "MainlineDialogue")
                        .WithMany("MainlineDialogue_CharacterImages")
                        .HasForeignKey("MainlineDialogueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainlineDialogue");
                });

            modelBuilder.Entity("VisualNovelGameDB.Entities.MainlineDialogue", b =>
                {
                    b.Navigation("MainlineDialogue_CharacterImages");
                });

            modelBuilder.Entity("VisualNovelGameDB.Entities.OptionCollection", b =>
                {
                    b.Navigation("ChoiceOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
